#***************************************************COMPUTER SCIENCE PROJECT******************************************************************
#TOPIC:- AUTOMOBILES IN SHOWROOM
#BY:-DEEPANSHI DEY

def Display():
    import mysql.connector as mc
    con=mc.connect(host="localhost", port="3307", user="root", password="deepanshi", database="dolly")
    mycur=con.cursor()
    mycur.execute("select * from automobiles " )
    data=mycur.fetchall()
    for i in data:
        print("**************************************************************")
        print("|","Item number =",i[0],"|")
        print("------------------------------------------------------------------------------- ")
        print("|","Model =",i[1],"|")
        print("--------------------------------------------------------------------------------")
        print("|","Company =",i[2],"|")
        print("--------------------------------------------------------------------------------")
        print("|","Available Colours =",i[3],"|")
        print("--------------------------------------------------------------------------------")
        print("|","Manufacturing Place =",i[4],"|")
        print("--------------------------------------------------------------------------------")
        print("|","Star =",i[5],"|")
        print("--------------------------------------------------------------------------------")
        print("|","Mileage =",i[6],"kmpl","|")
        print("--------------------------------------------------------------------------------")
        print("|","Price =",i[7],"Lakhs","|")
        print("--------------------------------------------------------------------------------")
        print("|","Availability =",i[8],"|")
        print("**************************************************************")
         
        
def Search():
    import mysql.connector as mc
    con=mc.connect(host="localhost", port="3307", user="root", password="deepanshi", database="dolly")
    mycur=con.cursor()
    print("**************Available Companies***************")
    print("1. Maruti")
    print("2. Honda")
    print("3. Hyundai")
    print("4. Mahindra")
    print("5. Tata")
    
    n=int(input("Enter your choice(1 to 5): "))
    if (n==1):
        mycur.execute("select * from automobiles where Company='%s' "%("maruti"))
        data=mycur.fetchall()
        for i in data:
             print("------------------------------------------------------------------------------------")
             print("|","Item number =",i[0],"|")
             print("|","Model =",i[1],"|")
             print("|","Company =",i[2],"|")
             print("|","Available Colours =",i[3],"|")
             print("|","Manufacturing Place =",i[4],"|")
             print("|","Star =",i[5],"|")
             print("|","Mileage =",i[6],"kmpl","|")
             print("|","Price =",i[7],"Lakhs","|")
             print("|","Availability =",i[8],"|")
             print("------------------------------------------------------------------------------------")   
    
           
    if  n==2:
       mycur.execute("select * from automobiles where Company='%s' "%("honda"))
       data=mycur.fetchall()
       for i in data:
           print("------------------------------------------------------------------------------------")
           print("|","Item number =",i[0],"|")
           print("|","Model =",i[1],"|")
           print("|","Company =",i[2],"|")
           print("|","Colour =",i[3],"|")
           print("|","Manufacturing Place =",i[4],"|")
           print("|","Star =",i[5],"|")
           print("|","Mileage =",i[6],"kmpl","|")
           print("|","Price =",i[7],"Lakhs","|")
           print("|","Availability =",i[8],"|")
           print("------------------------------------------------------------------------------------")


    if n==3:
       mycur.execute("select * from automobiles where Company='%s' "%("hyundai"))
       data=mycur.fetchall()
       for i in data:
           print("------------------------------------------------------------------------------------")
           print("|","Item number =",i[0],"|")
           print("|","Model =",i[1],"|")
           print("|","Company =",i[2],"|")
           print("|","Colour =",i[3],"|")
           print("|","Manufacturing Place =",i[4],"|")
           print("|","Star =",i[5],"|")
           print("|","Mileage =",i[6],"kmpl","|")
           print("|","Price =",i[7],"Lakhs","|")
           print("|","Availability =",i[8],"|")
           print("------------------------------------------------------------------------------------")


    if n==4:
       mycur.execute("select * from automobiles where Company='%s' "%("mahindra"))
       data=mycur.fetchall()
       for i in data:
           print("------------------------------------------------------------------------------------")
           print("|","Item number =",i[0],"|")
           print("|","Model =",i[1],"|")
           print("|","Company =",i[2],"|")
           print("|","Colour =",i[3],"|")
           print("|","Manufacturing Place =",i[4],"|")
           print("|","Star =",i[5],"|")
           print("|","Mileage =",i[6],"kmpl","|")
           print("|","Price =",i[7],"Lakhs","|")
           print("|","Availability =",i[8],"|")
           print("------------------------------------------------------------------------------------")

    if n==5:
       mycur.execute("select * from automobiles where Company='%s' "%("tata"))
       data=mycur.fetchall()
       for i in data:
           print("------------------------------------------------------------------------------------")
           print("|","Item number =",i[0],"|")
           print("|","Model =",i[1],"|")
           print("|","Company =",i[2],"|")
           print("|","Colour =",i[3],"|")
           print("|","Manufacturing Place =",i[4],"|")
           print("|","Star =",i[5],"|")
           print("|","Mileage =",i[6],"kmpl","|")
           print("|","Price =",i[7],"Lakhs","|")
           print("|","Availability =",i[8],"|")
           print("------------------------------------------------------------------------------------")



def Entry():
    import mysql.connector as mc
    con=mc.connect(host="localhost", port="3307", user="root", password="deepanshi", database="dolly")
    mycur=con.cursor()
    itno=int(input("Enter item number: "))
    model=input("Enter model name: ")
    company=input("Enter the company: ")
    colour=input("Enter the colour: ")
    mfac=input("Enter the manfacturing place: ")
    star=input("Enter how many star: ")
    mileage=input("Enter the mileage: ")
    price=input("Enter the price: ")
    availability=input("Enter how many in stock: ")
    mycur.execute("insert into automobiles values({},'{}','{}','{}','{}',{},{},{},{})".format(itno,model,company,colour,mfac,star,mileage,price,availability))
    con.commit()
    mycur.execute("select * from automobiles where Model='%s' "%(model))  
    data=mycur.fetchall()
    print("**********Entry successful***********")
    for i in data:
        print("------------------------------------------------------------------------------------")
        print("|","Item number =",i[0],"|")
        print("|","Model =",i[1],"|")
        print("|","Company =",i[2],"|")
        print("|","Colour =",i[3],"|")
        print("|","Manufacturing Place =",i[4],"|")
        print("|","Star =",i[5],"|")
        print("|","Mileage =",i[6],"kmpl","|")
        print("|","Price =",i[7],"Lakhs","|")
        print("|","Availability =",i[8],"|")
        print("------------------------------------------------------------------------------------")

    z=input("Do you want to give another entry? ")
    if (z=="yes"):
        Entry()

    
def Update():
     import mysql.connector as mc
     con=mc.connect(host="localhost", port="3307", user="root", password="deepanshi", database="dolly")
     mycur=con.cursor()
     print("*****Select One*****")
     print("1.update model")
     print("2.update company")
     print("3.update colour")
     print("4.update manufacturing place")
     print("5.update star")
     print("6.update mileage")
     print("7.update price")
     print("8.update availability")
     a=int(input("Enter your choice from 1 to 8: "))
     if a==1:
         w=input("Enter model name: ")
         mycur.execute("select Model from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("--------------------------------------------------------------------")
         print("The old Model name was", data)
         print("--------------------------------------------------------------------")
         n=input("Enter new name: ")
         mycur.execute("update automobiles set Model='%s' where Model='%s' "%(n,w))
         con.commit()
         mycur.execute("select * from automobiles where Model='%s' "%(n))
         data=mycur.fetchall()
         print("****The value has been updated****")
         for i in data:
             print("------------------------------------------------------------------------------------")
             print("|","Item number =",i[0],"|")
             print("|","Model =",i[1],"|")
             print("|","Company=",i[2],"|")
             print("|","Colour =",i[3],"|")
             print("|","Manufacturing Place =",i[4],"|")
             print("|","Star =",i[5],"|")
             print("|","Mileage =",i[6],"kmpl","|")
             print("|","Price =",i[7],"Lakhs","|")
             print("|","Availability =",i[8],"|")
             print("------------------------------------------------------------------------------------")


     elif a==2:
        w=input("Enter Model name: ")
        mycur.execute("select Company from automobiles where Model='%s' "%(w))
        data=mycur.fetchall()
        print("--------------------------------------------------------------------")
        print("The old company name was", data)
        print("--------------------------------------------------------------------")
        n=input("Enter new company name: ")
        mycur.execute("update automobiles set Company='%s' where Model='%s' "%(n,w))
        con.commit()
        mycur.execute("select * from automobiles where Model='%s' "%(w))
        data=mycur.fetchall()
        print("****The value has been updated****")
        for i in data:
            print("------------------------------------------------------------------------------------")
            print("|","Item number =",i[0],"|")
            print("|","Model =",i[1],"|")
            print("|","Company =",i[2],"|")
            print("|","Colour =",i[3],"|")
            print("|","Manufacturing Place =",i[4],"|")
            print("|","Star =",i[5],"|")
            print("|","Mileage =",i[6],"kmpl","|")
            print("|","Price =",i[7],"Lakhs","|")
            print("|","Availability =",i[8],"|")
            print("------------------------------------------------------------------------------------")


     elif a==3:
        w=input("Enter Model name: ")
        mycur.execute("select Colour from automobiles where Model='%s' "%(w))
        data=mycur.fetchall()
        print("--------------------------------------------------------------------")
        print("The old colour was", data)
        print("--------------------------------------------------------------------")
        n=input("Enter new colour: ")
        mycur.execute("update automobiles set Colour='%s' where Model='%s' "%(n,w))
        con.commit()
        mycur.execute("select * from automobiles where Model='%s' "%(w))
        data=mycur.fetchall()
        print("****The value has been updated****")
        for i in data:
            print("------------------------------------------------------------------------------------")
            print("|","Item number =",i[0],"|")
            print("|","Model =",i[1],"|")
            print("|","Company =",i[2],"|")
            print("|","Colour =",i[3],"|")
            print("|","Manufacturing Place =",i[4],"|")
            print("|","Star =",i[5],"|")
            print("|","Mileage =",i[6],"kmpl","|")
            print("|","Price =",i[7],"Lakhs","|")
            print("|","Availability =",i[8],"|")
            print("------------------------------------------------------------------------------------")


     elif a==4:
         w=input("Enter Model name: ") 
         mycur.execute("select Manufacturing_place from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("--------------------------------------------------------------------")
         print("The old Mnufacturing place was", data)
         print("--------------------------------------------------------------------") 
         n=input("Enter new Manufacturing place: ")
         mycur.execute("update automobiles set Manufacturing_place='%s' where Model='%s' "%(n,w))
         con.commit()
         mycur.execute("select * from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("****The value has been updated****")
         for i in data:
             print("------------------------------------------------------------------------------------")
             print("|","Item number =",i[0],"|")
             print("|","Model =",i[1],"|")
             print("|","Company =",i[2],"|")
             print("|","Colour =",i[3],"|")
             print("|","Manufacturing Place =",i[4],"|")
             print("|","Star =",i[5],"|")
             print("|","Mileage =",i[6],"kmpl","|")
             print("|","Price =",i[7],"Lakhs","|")
             print("|","Availability =",i[8],"|")
             print("------------------------------------------------------------------------------------")
  

     elif a==5:
        w=input("Enter Model name: ")  
        mycur.execute("select Star from automobiles where Model='%s' "%(w))
        data=mycur.fetchall()
        print("--------------------------------------------------------------------")
        print("The old value was", data)
        print("--------------------------------------------------------------------")
        n=input("Enter new value: ")
        mycur.execute("update automobiles set Star='%s' where Model='%s' "%(n,w))
        con.commit()
        mycur.execute("select * from automobiles where Model='%s' "%(w))
        data=mycur.fetchall()
        print("****The value has been updated****")
        for i in data:
            print("------------------------------------------------------------------------------------")
            print("|","Item number =",i[0],"|")
            print("|","Model =",i[1],"|")
            print("|","Company =",i[2],"|")
            print("|","Colour =",i[3],"|")
            print("|","Manufacturing Place =",i[4],"|")
            print("|","Star =",i[5],"|")
            print("|","Mileage =",i[6],"kmpl","|")
            print("|","Price =",i[7],"Lakhs","|")
            print("|","Availability =",i[8],"|")
            print("------------------------------------------------------------------------------------")


     elif a==6:
         w=input("Enter Model name: ") 
         mycur.execute("select Mileage from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("--------------------------------------------------------------------")
         print("Your old value was", data,"kmpl")
         print("--------------------------------------------------------------------")
         n=input("Enter new value: ")
         mycur.execute("update automobiles set Mileage='%s' where Model='%s' "%(n,w))
         con.commit()
         mycur.execute("select * from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("****The value has been updated****")
         for i in data:
             print("------------------------------------------------------------------------------------")
             print("|","Item number =",i[0],"|")
             print("|","Model =",i[1],"|")
             print("|","Company =",i[2],"|")
             print("|","Colour =",i[3],"|")
             print("|","Manufacturing Place =",i[4],"|")
             print("|","Star =",i[5],"|")
             print("|","Mileage =",i[6],"kmpl","|")
             print("|","Price =",i[7],"Lakhs","|")
             print("|","Availability =",i[8],"|")
             print("------------------------------------------------------------------------------------")


     elif a==7:
         w=input("Enter Model name: ") 
         mycur.execute("select Price from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("--------------------------------------------------------------------")
         print("Your old price was", data,"lakhs")
         print("--------------------------------------------------------------------")
         n=input("Enter new price: ")
         mycur.execute("update automobiles set Price='%s' where Model='%s' "%(n,w))
         con.commit()
         mycur.execute("select * from automobiles  where Model='%s' "%(w))
         data=mycur.fetchall()
         print("****The value has been updated****")
         for i in data:
             print("------------------------------------------------------------------------------------")
             print("|","Item number =",i[0],"|")
             print("|","Model =",i[1],"|")
             print("|","Company =",i[2],"|")
             print("|","Colour =",i[3],"|")
             print("|","Manufacturing Place =",i[4],"|")
             print("|","Star =",i[5],"|")
             print("|","Mileage =",i[6],"kmpl","|")
             print("|","Price =",i[7],"Lakhs","|")
             print("|","Availability =",i[8],"|")
             print("------------------------------------------------------------------------------------")


     elif a==8:
         w=input("Enter Model name: ") 
         mycur.execute("select Availability from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("--------------------------------------------------------------------")
         print("Your old value was", data)
         print("--------------------------------------------------------------------")
         n=input("Enter new value: ")
         mycur.execute("update automobiles set Availability='%s' where Model='%s' "%(n,w))
         con.commit()
         mycur.execute("select * from automobiles where Model='%s' "%(w))
         data=mycur.fetchall()
         print("****The value has been updated****")
         for i in data:
             print("------------------------------------------------------------------------------------")
             print("|","Item number =",i[0],"|")
             print("|","Model =",i[1],"|")
             print("|","Company =",i[2],"|")
             print("|","Colour =",i[3],"|")
             print("|","Manufacturing Place =",i[4],"|")
             print("|","Star =",i[5],"|")
             print("|","Mileage =",i[6],"kmpl","|")
             print("|","Price =",i[7],"Lakhs","|")
             print("|","Availability =",i[8],"|")
             print("------------------------------------------------------------------------------------")


         

def Delete():
     import mysql.connector as mc
     con=mc.connect(host="localhost", port="3307", user="root", password="deepanshi", database="dolly")
     mycur=con.cursor()
     d=input("Enter the Model of the product you want to delete: ")
     mycur.execute("select * from automobiles where Model='%s' "%(d))
     data=mycur.fetchall()
     print("---------------------------------------------------------------------------------------------")
     for i in data:
         print("------------------------------------------------------------------------------------")
         print("|","Item number =",i[0],"|")
         print("|","Model =",i[1],"|")
         print("|","Company =",i[2],"|")
         print("|","Colour =",i[3],"|")
         print("|","Manufacturing Place =",i[4],"|")
         print("|","Star =",i[5],"|")
         print("|","Mileage =",i[6],"kmpl","|")
         print("|","Price =",i[7],"Lakhs","|")
         print("|","Availability =",i[8],"|")
         print("------------------------------------------------------------------------------------")
     print("****This is the model",d,"****")
     print("---------------------------------------------------------------------------------------------")
     a=input("Do you want to continue deletion? ")
     if (a=="yes"):
         mycur.execute("delete from automobiles where Model='%s' "%(d))
         con.commit()
         print("Details of the Model",d,"has been deleted")
         mycur.execute("select * from automobiles")
         data=mycur.fetchall()
         for i in data:
             print("------------------------------------------------------------------------------------")
             print("|","Item number =",i[0],"|")
             print("|","Model =",i[1],"|")
             print("|","Company =",i[2],"|")
             print("|","Colour =",i[3],"|")
             print("|","Manufacturing Place =",i[4],"|")
             print("|","Star =",i[5],"|")
             print("|","Mileage =",i[6],"kmpl","|")
             print("|","Price =",i[7],"Lakhs","|")
             print("|","Availability =",i[8],"|")
  
while True:
    print("***************WELCOME TO AUTOMOBILE MANAGEMENT SYSTEM***************")
    print("***MAIN MENU***")
    print("PRESS 1. To see the details of all the cars present in showroom")
    print("PRESS 2. To see the details of a car")
    print("PRESS 3. To enter the details of a car ")
    print("PRESS 4. To update the details of a car ")
    print("PRESS 5. To delete the details of a car ")
    print("PRESS 6. To exit ")
    q=int(input("Please enter your choise from 1-6: "))
    if q==1:
        Display()
    if q==2:
        Search()
    if q==3:
        Entry()
    if q==4:
        Update()
    if q==5:
        Delete()
    if q==6:
        print("*************THANK YOU************")
        break
    
